### PR TITLE
add jaccount captcha solver

### PR DESCRIPTION
**Pull request by danyang685**
Usage

- path: `/captcha-solver`
- form-data:
    | field | is required | description                |
    | ----- | ----------- | -------------------------- |
    | image | required    | the raw captcha image file |
- json response:
    | field   | description                |
    | ------- | -------------------------- |
    | `error` | `succeed` or error message |
    | `image` | captcha inference result   |

### CODE REVIEW

**Review by skyzh — COMMENTED** [review]
It seems that there is no Dockerfile under https://github.com/danyang685/jaccount-captcha-solver . How does it build?

**Comment by skyzh** [comment]
By the way, I would recommend adding an authentication behind this API. Making it available to public doesn't seem to be a good idea.

**Comment by danyang685** [comment]
> It seems that there is no Dockerfile under https://github.com/danyang685/jaccount-captcha-solver . How does it build?

The code is located at https://github.com/danyang685/jaccount-captcha-solver/tree/service .

**Review by skyzh — APPROVED** [review]
LGTM.
* Please add HTTP basic authentication if possible.
* `debug` should be `False` at https://github.com/danyang685/jaccount-captcha-solver/blob/service/online.py#L52

**Pull request merged**
